import {StyleSheet} from 'react-native';
import {Colors} from '../../constants/color.constants';
import {DEVICE} from '../../constants/devices.constant';
import {FontSize} from '../../constants/fontsize.constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.Solitaire,
  },
  imageProductBackground: {
    backgroundColor: Colors.Black,
    width: '100%',
    height: 200,
    paddingHorizontal: '3%',
    paddingTop: 10,
  },
  imageContainer: {
    marginLeft: '8%',
    width: '80%',
    height: 200,
    marginTop: -120,
  },
  imageWrapper: {
    width: '100%',
    height: '100%',
    borderRadius: 30,
    overflow: 'hidden',
    backgroundColor: 'transparent',
    borderColor: 'white',
    borderWidth: 1,
  },
  productInformation: {
    width: '50%',
    marginTop: 20,
    marginLeft: '10%',
  },
  productDescription: {
    fontSize: FontSize.Large,
    fontWeight: '400',
    marginLeft: '5%',
    color: '#FFFFFF90',
  },
  productDate: {
    fontWeight: '400',
    fontSize: FontSize.Small,
    marginLeft: '5%',
    color: '#FFFFFF90',
  },
  farmerInformation: {
    marginTop: 20,
  },
  farmerTitle: {
    fontSize: FontSize.Normal,
    fontWeight: '600',
    marginBottom: 10,
  },
  farmerInfo: {
    fontSize: FontSize.Small,
    fontWeight: '400',
  },
  contentContainer: {
    width: '100%',
    flexDirection: 'row',
    marginTop: 10,
  },
  rightButton: {
    width: '30%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  inStockUp: {
    width: '90%',
    backgroundColor: Colors.DarkFuelGreen,
    borderRadius: 80,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 2,
    paddingVertical: 7,
  },
  inStockUpTitle: {
    fontSize: FontSize.NormalSmall,
    fontWeight: '500',
  },
  inStockUpNumber: {
    fontSize: FontSize.NormalSmall,
    fontWeight: '500',
  },
  viewShopContainer: {
    width: '100%',
    marginTop: 30,
    alignItems: 'center',
  },
  viewShopTitle: {
    fontSize: FontSize.Small,
    fontWeight: '400',
    color: Colors.DarkFuelGreen,
  },
  phoneNowTitle: {
    fontSize: FontSize.Small,
    fontWeight: '400',
    color: Colors.DarkFuelGreen,
  },
  buttonContainer: {
    width: '80%',
    alignItems: 'center',
    paddingVertical: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.DarkFuelGreen,
    marginBottom: 10,
  },
  headerContainer: {},
  iconImage: {},
  bottomSheetContainer: {
    paddingHorizontal: '5%',
    paddingTop: 20,
    backgroundColor: Colors.TimberGreen,
  },
  bottomTitle: {
    color: Colors.Solitaire,
    fontSize: FontSize.Normal,
    textAlign: 'center',
    marginVertical: 10,
  },
  disable: {
    color: Colors.DarkGreen50,
    borderColor: Colors.DarkFuelGreen50,
  },
  submitButton: {
    backgroundColor: Colors.Solitaire,
    marginVertical: 20,
    borderRadius: 5,
  },
  submitTitle: {
    color: Colors.TimberGreen,
    fontSize: FontSize.MediumSmall,
    fontWeight: '600',
  },
  inputTitle: {
    fontSize: FontSize.Normal,
    color: Colors.Solitaire,
  },
  inputText: {
    borderBottomWidth: 1,
    borderColor: Colors.Solitaire90,
    color: Colors.Solitaire,
  },
  infoInputContainer: {
    marginVertical: 10,
  },
  addressInput: {
    width: '100%',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.DarkGreen,
    height: 48,
    justifyContent: 'center',
    paddingLeft: 10,
    marginTop: 10,
  },
  inputAddressInformationContainer: {
    marginTop: 5,
  },
  addressButton: {
    marginTop: 20,
  },
  defaultAddressContainer: {
    borderColor: Colors.DarkGreen,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginTop: 5,
    borderRadius: 10,
  },

  imageBackground: {
    width: DEVICE.WIDTH,
    height: 350,
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  productImageMiniContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '90%',
    alignSelf: 'center',
    padding: 10,
    justifyContent: 'center',
  },
  productImageMini: {
    width: 30,
    height: 30,
    borderRadius: 30,
    marginHorizontal: 7,
    overflow: 'hidden',
  },
  productMini: {
    width: 30,
    height: 30,
    resizeMode: 'stretch',
  },
  productName: {
    color: Colors.TimberGreen,
    fontSize: FontSize.Large,
    fontWeight: '800',
    textAlign: 'center',
    marginVertical: 10,
  },
  generalInfoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginVertical: 10,
  },
  longLine: {
    width: '80%',
    height: 1,
    backgroundColor: Colors.TimberGreen,
    alignSelf: 'center',
  },
  shortLine: {
    width: '60%',
    height: 1,
    backgroundColor: Colors.TimberGreen,
    alignSelf: 'center',
  },
  descriptionTitle: {
    color: Colors.TimberGreen,
    fontSize: FontSize.Large,
    fontWeight: '600',
    textAlign: 'center',
    marginVertical: 10,
  },
  description: {
    width: '80%',
    color: Colors.TimberGreen,
    fontSize: FontSize.SemiSmall,
    fontWeight: '400',
    textAlign: 'center',
    alignSelf: 'center',
    marginBottom: 20,
  },
  orderButton: {
    width: '60%',
    height: 40,
    borderColor: Colors.TimberGreen,
    borderWidth: 1,
    borderRadius: 0,
    alignSelf: 'center',
    marginVertical: 20,
  },
  buttonTitle: {
    color: Colors.TimberGreen,
  },
  imageProductContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingTop: 60,
  },
  productImage: {
    width: 200,
    height: 200,
    borderRadius: 150,
    overflow: 'hidden',
  },
  pImage: {
    width: 200,
    height: 200,
    resizeMode: 'stretch',
  },
  farmerCard: {
    flexDirection: 'row',
    width: '80%',
    alignItems: 'center',
    marginLeft: '5%',
    marginVertical: 10,
  },
  farmerImageContainer: {
    width: 40,
    height: 40,
    overflow: 'hidden',
    borderRadius: 40,
  },
  farmerImage: {
    width: 40,
    height: 40,
    resizeMode: 'stretch',
  },
  farmerInformationContainer: {
    width: '60%',
    paddingLeft: '2%',
  },
  farmerName: {
    color: Colors.TimberGreen,
    fontWeight: '600',
    fontSize: FontSize.Normal,
    width: '100%',
  },
  farmerLocation: {
    color: Colors.TimberGreen,
    fontWeight: '400',
    fontSize: FontSize.SemiSmall,
    width: '95%',
  },
  contactButton: {
    width: '18%',
    borderRadius: 10,
    backgroundColor: Colors.Sidecar,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '2%',
  },
  contactIcon: {
    width: 20,
    height: 20,
    resizeMode: 'stretch',
  },
  wrapperStyle: {
    marginVertical: 10,
    paddingHorizontal: 0,
  },
  smallRadioButton: {
    width: 20,
    height: 20,
    overflow: 'hidden',
    marginVertical: 5,
  },
  marginTop10: {
    marginTop: 10,
  },
});
