export const ScreenName = {
  LoginScreen: 'LoginScreen',
  SignUpScreen: 'SignupScreen',
  ProductDetailScreen: 'ProductDetailScreen',
  SearchScreen: 'SearchScreen',
  CategoryScreen: 'CategoryScreen',
  StoreDetailScreen: 'StoreDetailScreen',
  ProductWaitingScreen: 'ProductWaitingScreen',
  ProductDeliveryScreen: 'ProductDeliveryScreen',
  ProductHistoryScreen: 'ProductHistoryScreen',
  NewDetailScreen: 'NewDetailScreen',
  MessageDetailScreen: 'MessageDetailScreen',
  WaitingScreen: 'WaitingScreen',
  HistoryScreen: 'HistoryScreen',
  ChangePasswordScreen: 'ChangePasswordScreen',
  UserProfileScreen: 'UserProfileScreen',
  LanguageScreen: 'LanguageScreen',
  DeliveryScreen: 'DeliveryScreen',
};
